# Generated by Django 4.2.10 on 2024-02-10 15:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_timer',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=30), null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(days=1)), django.core.validators.MaxValueValidator(limit_value=datetime.timedelta(days=60))], verbose_name='Bid Timer'),
        ),
    ]
