# Generated by Django 4.2.10 on 2024-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_rename_content_listing_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='manufacturer',
            field=models.CharField(choices=[('Audemars Piguet', 'Audemars Piguet'), ('Blancpain', 'Blancpain'), ('Breguet', 'Breguet'), ('Breitling', 'Breitling'), ('Bulgari', 'Bulgari'), ('Cartier', 'Cartier'), ('Chopard', 'Chopard'), ('Citizen', 'Citizen'), ('Fossil', 'Fossil'), ('Girard-Perregaux', 'Girard-Perregaux'), ('Hamilton', 'Hamilton'), ('Hublot', 'Hublot'), ('IWC Schaffhausen', 'IWC Schaffhausen'), ('Jaeger-LeCoultre', 'Jaeger-LeCoultre'), ('Longines', 'Longines'), ('Montblanc', 'Montblanc'), ('Omega', 'Omega'), ('Oris', 'Oris'), ('Panerai', 'Panerai'), ('Patek Philippe', 'Patek Philippe'), ('Piaget', 'Piaget'), ('Rado', 'Rado'), ('Raymond Weil', 'Raymond Weil'), ('Rolex', 'Rolex'), ('Seiko', 'Seiko'), ('TAG Heuer', 'TAG Heuer'), ('Tissot', 'Tissot'), ('Tudor', 'Tudor'), ('Ulysse Nardin', 'Ulysse Nardin'), ('Vacheron Constantin', 'Vacheron Constantin'), ('Zenith', 'Zenith')], default='None Selected', max_length=100),
        ),
    ]
