# Generated by Django 4.2.10 on 2024-02-26 16:47

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0009_listing_image_1_listing_image_2_listing_image_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_3',
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buy.listing')),
            ],
        ),
    ]
