# Generated by Django 4.2.10 on 2024-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0010_remove_listing_image_1_remove_listing_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Listed')], default=1),
        ),
    ]
