# Generated by Django 4.2.10 on 2024-03-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
